apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hello-appset
  namespace: openshift-gitops
spec:
  generators:
    - list:
        elements:
          - env: dev
            values-dir: /application/values/values-dev.yaml
          - env: pre
            values-dir: /application/values/values-pre.yaml
          - env: pro
            values-dir: /application/values/values-pro.yaml
    - git:
        files:
          - path: '{{values-dir}}'
        repoURL: 'https://github.com/bizcochillo/test-gitops.git'
        revision: main
  template:
    metadata:
      annotations:
        argocd.argoproj.io/manifest-generate-paths: '{{values-dir}};/helm/hello'
      name: 'hello-appset-{{env}}'
    spec:
      destination:
        namespace: 'hello-gitops-{{env}}'
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        helm:
          valueFiles:
            - '{{values-dir}}'
        path: helm/hello
        repoURL: 'https://github.com/bizcochillo/test-gitops.git'
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        managedNamespaceMetadata:
          labels:
            argocd.argoproj.io/managed-by: openshift-gitops
        syncOptions:
          - CreateNamespace=true